name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")
favsport = input("Enter your favourite sport: ")
dreamcmp = input("Enter your dream company: ")
print("Name: ", name)
print("Age: ", age)
print("City: ", city)
print("Favourite Sport: ", favsport)
print("Dream Company: ", dreamcmp)